name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install aux4
        run: npm install -g aux4

      - name: Install dependencies
        run: |
          aux4 aux4 pkger install agent/manager
          aux4 aux4 pkger install agent/worker
          aux4 aux4 pkger install aux4/queue

      - name: Run tests
        run: cd package && aux4 test run

      - name: Publish package
        uses: aux4/publish-package-action@v1
        with:
          package: package
        env:
          AUX4_API_KEY: ${{ secrets.AUX4_API_KEY }}
